### ISSUE TITLE
Simple interface - peer conenction doesn't work [Ubuntu 24.04LTS]

### ISSUE THREAD

**Issue by sireaev** [leon3s/wireguard-gui#107]
Hello there,

Ubuntu 24.04LTS

Installed Wireguard and wireguard-gui from leon3s, just added a simple configuration:
```
[Interface]
PrivateKey = 
Address = 
DNS =

[Peer]
PublicKey = 
PresharedKey =
AllowedIPs = 
Endpoint =
PersistentKeepAlive = 25
```

The wireguard-gui manages to connect (showing green button) and tray, but though trying to connect to a website outside my network it outputs 403. Though on other platforms like Windows or configuring manually works well, using wg wg-quick etc...

**Comment by leon3s** [comment]
Hey!

First thank you to have taken the time to open an issue,
wireguard-gui use wg-quick as back-end to setup the wireguard connection.
So if it's work using the wg-quick command it should work in the gui.

I don't really have time at the moment to investigate further on the issue till 16 June.
And the config look pretty empty to me to actually work.

```sh
╰─ sudo cat /etc/wireguard/wgtest.conf
[Interface]
PrivateKey = 
Address = 
DNS =

[Peer]
PublicKey = 
PresharedKey =
AllowedIPs = 
Endpoint =
PersistentKeepAlive = 25
```

```sh
sudo wg-quick up wgtest            
[#] ip link add wgtest type wireguard
[#] wg setconf wgtest /dev/fd/63
Line unrecognized: `PrivateKey='
Configuration parsing error
[#] ip link delete dev wgtest
```
