### ISSUE TITLE
Not working Ubuntu 24.04 lts

### ISSUE THREAD

**Issue by dreykanbern** [leon3s/wireguard-gui#118]
I installed wireguard, then the wireguard gui itself, gave permission to manage the network manager through system settings,
I created a profile named: UbuntuUSA
Settings:

[Interface]
PrivateKey = my private key
Address = 10.8.0.3/24
DNS = 1.1.1.1

[Peer]
PublicKey = my public key
PresharedKey = my preshared key
AllowedIPs = 0.0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 77.238.228.246:51820

These settings I just downloaded from my server where I deployed this library 
https://github.com/wg-easy/wg-easy#updating and when connecting via `wq-quick up` on my own, everything works.

but with this gui does not work, it says that I am successfully connected, green light is on, but ip does not change, remains the same as it was before vpn connection.

![image](https://github.com/leon3s/wireguard-gui/assets/83606022/ae8bc6a8-2632-41d3-aeed-fcbf4eb5e631)![image](https://github.com/leon3s/wireguard-gui/assets/83606022/0b328a4b-6d0d-413e-8dfc-a589e579706b)

**Comment by leon3s** [comment]
Hey, thank to have took time to open an issue, are you using the snap version or the .deb version ?

**Comment by dreykanbern** [comment]
> Hey, thank to have took time to open an issue, are you using the snap version or the .deb version ?

Greetings, I used the snap version from this thread

![image](https://github.com/leon3s/wireguard-gui/assets/83606022/e1ff6a4d-4ba7-4aa4-8e40-6ba52630a889)

**Comment by bratanon** [comment]
deb 0.1.2-stable seems to work with 24.04

**Comment by leon3s** [comment]
Closing this as i believe it's resolved.
