### ISSUE TITLE
Save profile confusing

### ISSUE THREAD

**Issue by melroy89** [leon3s/wireguard-gui#144]
Seems to works great. However, when I created a new profile and pressed "Save" button. The screen was still in the new profile, I thought I didn't press it correctly. I was confused, when pressing again, it said "Profile already exists". Meaning it did save correctly.

Please, show a pop-up or something that saving of a profile went successfully. And/or go back to the main window after the user pressed on the Save button.

Thanks!

I hope I'm clear, if not let me know. I'm using your latest release (0.1.2).

Keep going! I love this simple GUI! <3

**Comment by leon3s** [comment]
Hey thanks for the report, this is a regression from previous version, the modal should close by itself i'll provide a fix during the incomming week!

**Comment by melroy89** [comment]
> Hey thanks for the report, this is a regression from previous version, the modal should close by itself i'll provide a fix during the incomming week!

Ah ok! Thanks for your fast reply!

_Small tip:_ Maybe show your version somewhere on the screen, left top, in the title bar or somewhere (I also couldn't find `--version`). So it's easier for me (but also for you) which version I run of wireguard-gui.

**Comment by leon3s** [comment]
`0.1.3` have been released let me know if it work for you

**Comment by melroy89** [comment]
Great! I will test it right now. 🎉

**Comment by melroy89** [comment]
Yup. Works great now! Version at the top now, nice. And indeed the modal is now closed on save!

**Comment by leon3s** [comment]
Great!
