### ISSUE TITLE
Blank GUI on first install/open - Ubuntu 22.04

### ISSUE THREAD

**Issue by afonsosantos** [leon3s/wireguard-gui#47]
Hey!

Just installed via Snap on Ubuntu 22.04 (using snap CLI) and the GUI is empty, like the screenshot below:

![image](https://github.com/leon3s/wireguard-gui/assets/46262740/bde91f8d-1fb6-4389-a52c-55acdbd54d7b)

Thanks!

**Comment by leon3s** [comment]
Hey, thanks for the bug report, currently the snap version is not working, see https://github.com/leon3s/wireguard-gui/issues/6

I recommand you to use the .deb package you can find it there: https://github.com/leon3s/wireguard-gui/releases/tag/0.1.1-stable

**Comment by afonsosantos** [comment]
Thank you for the response.
The .deb package is working just fine, hence closing this issue.
